name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
    - '**/*.swift'
    - '**/*.c'
    - '**/*.h'
    - '.github/workflows/**'
    - 'Package.swift'
  pull_request:
    branches: [ main ]
    paths:
    - '**/*.swift'
    - '**/*.c'
    - '**/*.h'
    - '.github/workflows/**'
    - 'Package.swift'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Build
      run: swift build

    - name: Test
      run: swift test
