name: Swift Dependency Submission

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'Package.swift'
    - 'Package.resolved'
  pull_request:
    branches: [ main ]
    paths:
    - 'Package.swift'
    - 'Package.resolved'

permissions:
  contents: write

jobs:
  submit-dependencies:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Submit dependencies
      uses: vapor-community/swift-dependency-submission@e233cf7a4e1e59e87e128a80e7f92467f0640e21 # v0.1
      with:
        force: true
