name: Swift Dependency Submission

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'Package.swift'
    - 'Package.resolved'
  pull_request:
    branches: [ main ]
    paths:
    - 'Package.swift'
    - 'Package.resolved'

permissions:
  contents: write

jobs:
  submit-dependencies:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Submit dependencies
      uses: vapor-community/swift-dependency-submission@e233cf7a4e1e59e87e128a80e7f92467f0640e21 # v0.1
      with:
        force: true
